package com.resume.pojo;

import java.util.Date;

/**
 * 和用户信息有关的类
 *
 * @author danny
 * @date 2020/1/27
 */
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_addr
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private String emailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_password
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private String emailPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.imap_server
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private String imapServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.smtp_server
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private String smtpServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pop3_server
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private String pop3Server;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modified
     *
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_addr
     *
     * @return the value of user.email_addr
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_addr
     *
     * @param emailAddr the value for user.email_addr
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr == null ? null : emailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_password
     *
     * @return the value of user.email_password
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public String getEmailPassword() {
        return emailPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_password
     *
     * @param emailPassword the value for user.email_password
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setEmailPassword(String emailPassword) {
        this.emailPassword = emailPassword == null ? null : emailPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.imap_server
     *
     * @return the value of user.imap_server
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public String getImapServer() {
        return imapServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.imap_server
     *
     * @param imapServer the value for user.imap_server
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setImapServer(String imapServer) {
        this.imapServer = imapServer == null ? null : imapServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.smtp_server
     *
     * @return the value of user.smtp_server
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public String getSmtpServer() {
        return smtpServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.smtp_server
     *
     * @param smtpServer the value for user.smtp_server
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setSmtpServer(String smtpServer) {
        this.smtpServer = smtpServer == null ? null : smtpServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pop3_server
     *
     * @return the value of user.pop3_server
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public String getPop3Server() {
        return pop3Server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pop3_server
     *
     * @param pop3Server the value for user.pop3_server
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setPop3Server(String pop3Server) {
        this.pop3Server = pop3Server == null ? null : pop3Server.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_create
     *
     * @return the value of user.gmt_create
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_create
     *
     * @param gmtCreate the value for user.gmt_create
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_modified
     *
     * @return the value of user.gmt_modified
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_modified
     *
     * @param gmtModified the value for user.gmt_modified
     * @mbg.generated Thu Feb 06 13:29:56 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("User{");
        sb.append("id=").append(id);
        sb.append(", username='").append(username).append('\'');
        sb.append(", password='").append(password).append('\'');
        sb.append(", emailAddr='").append(emailAddr).append('\'');
        sb.append(", emailPassword='").append(emailPassword).append('\'');
        sb.append(", imapServer='").append(imapServer).append('\'');
        sb.append(", smtpServer='").append(smtpServer).append('\'');
        sb.append(", pop3Server='").append(pop3Server).append('\'');
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append('}');
        return sb.toString();
    }
}
